import { ReduxProvider } from '@/redux/features/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './components/Providers';
import AppBar from './layouts/login/AppBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'University Management System',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}
export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppBar />
          <ReduxProvider>{props.children}</ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
