import { ReduxProvider } from '@/redux/features/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './components/Providers';
const inter = Inter({ subsets: ['latin'] });
import Navbar from './navbar';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
export const metadata: Metadata = {
  title: 'University Management System',
  description: 'Generated by create next app',
};
interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return ( 
    <html lang="en">
      <body className={inter.className}>

        <Providers>
          {/* <AppBar /> */}
          <ReduxProvider>
          <StyledComponentsRegistry>
          <Navbar />
            {props.children}
            </StyledComponentsRegistry>
            </ReduxProvider>
        </Providers>

      </body>
    </html>

  );
}
